version: "3.9"
services:
  printer:
    image: print_service
    volumes:
      - ./app/:/app
      - ./lualatex/templates:/tex_test
    ports:
      - '3000:3000'
    environment:
      SECRET_KEY_BASE: 3e4289581b4b6a1ff1ae43bf24a238c3c8231ad7ec4db5ddb39a956cd84d104d089179dfe449d1c2737dfcad53f613b30bea63f0029eca24615787886151d0f1
      RAILS_ENV: development
  redis:
    image: redis